# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assist.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_assist(object):
    def setupUi(self, assist):
        assist.setObjectName("assist")
        assist.setWindowModality(QtCore.Qt.ApplicationModal)
        assist.resize(782, 489)
        assist.setFixedSize(782, 489)
        self.verticalLayoutWidget = QtWidgets.QWidget(assist)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(680, 10, 81, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pb_start = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pb_start.setObjectName("pb_start")
        self.verticalLayout.addWidget(self.pb_start)
        self.pb_pause = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pb_pause.setObjectName("pb_pause")
        self.verticalLayout.addWidget(self.pb_pause)
        self.pb_stop = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pb_stop.setObjectName("pb_stop")
        self.verticalLayout.addWidget(self.pb_stop)
        self.pb_clear = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pb_clear.setObjectName("pb_clear")
        self.verticalLayout.addWidget(self.pb_clear)
        self.tb_logs = QtWidgets.QTextBrowser(assist)
        self.tb_logs.setGeometry(QtCore.QRect(20, 360, 741, 121))
        self.tb_logs.setObjectName("tb_logs")
        self.grb_list = QtWidgets.QGroupBox(assist)
        self.grb_list.setGeometry(QtCore.QRect(20, 90, 631, 171))
        self.grb_list.setObjectName("grb_list")
        self.layoutWidget = QtWidgets.QWidget(self.grb_list)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 60, 571, 20))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chb_dtu = QtWidgets.QCheckBox(self.layoutWidget)
        self.chb_dtu.setObjectName("chb_dtu")
        self.horizontalLayout_2.addWidget(self.chb_dtu)
        self.chb_wtu = QtWidgets.QCheckBox(self.layoutWidget)
        self.chb_wtu.setObjectName("chb_wtu")
        self.horizontalLayout_2.addWidget(self.chb_wtu)
        self.chb_smen = QtWidgets.QCheckBox(self.layoutWidget)
        self.chb_smen.setObjectName("chb_smen")
        self.horizontalLayout_2.addWidget(self.chb_smen)
        self.chb_ybiao = QtWidgets.QCheckBox(self.layoutWidget)
        self.chb_ybiao.setObjectName("chb_ybiao")
        self.horizontalLayout_2.addWidget(self.chb_ybiao)
        self.chb_wkuang = QtWidgets.QCheckBox(self.layoutWidget)
        self.chb_wkuang.setObjectName("chb_wkuang")
        self.horizontalLayout_2.addWidget(self.chb_wkuang)
        self.layoutWidget1 = QtWidgets.QWidget(self.grb_list)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 20, 151, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.chb_zgui = QtWidgets.QCheckBox(self.layoutWidget1)
        self.chb_zgui.setObjectName("chb_zgui")
        self.horizontalLayout_3.addWidget(self.chb_zgui, 0, QtCore.Qt.AlignLeft)
        self.lab_zgui = QtWidgets.QLabel(self.layoutWidget1)
        self.lab_zgui.setObjectName("lab_zgui")
        self.horizontalLayout_3.addWidget(self.lab_zgui)
        self.spb_zgui = QtWidgets.QSpinBox(self.layoutWidget1)
        self.spb_zgui.setObjectName("spb_zgui")
        self.horizontalLayout_3.addWidget(self.spb_zgui)
        self.layoutWidget2 = QtWidgets.QWidget(self.grb_list)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 100, 571, 18))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.chb_bpai = QtWidgets.QCheckBox(self.layoutWidget2)
        self.chb_bpai.setObjectName("chb_bpai")
        self.horizontalLayout_4.addWidget(self.chb_bpai)
        self.chb_mpai = QtWidgets.QCheckBox(self.layoutWidget2)
        self.chb_mpai.setObjectName("chb_mpai")
        self.horizontalLayout_4.addWidget(self.chb_mpai)
        self.chb_haidi = QtWidgets.QCheckBox(self.layoutWidget2)
        self.chb_haidi.setObjectName("chb_haidi")
        self.horizontalLayout_4.addWidget(self.chb_haidi)
        self.chb_mihunt = QtWidgets.QCheckBox(self.layoutWidget2)
        self.chb_mihunt.setObjectName("chb_mihunt")
        self.horizontalLayout_4.addWidget(self.chb_mihunt)
        self.chb_jylian = QtWidgets.QCheckBox(self.layoutWidget2)
        self.chb_jylian.setObjectName("chb_jylian")
        self.horizontalLayout_4.addWidget(self.chb_jylian)
        self.layoutWidget3 = QtWidgets.QWidget(self.grb_list)
        self.layoutWidget3.setGeometry(QtCore.QRect(240, 20, 149, 22))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.chb_fben = QtWidgets.QCheckBox(self.layoutWidget3)
        self.chb_fben.setObjectName("chb_fben")
        self.horizontalLayout_6.addWidget(self.chb_fben)
        self.lab_FuBen = QtWidgets.QLabel(self.layoutWidget3)
        self.lab_FuBen.setObjectName("lab_FuBen")
        self.horizontalLayout_6.addWidget(self.lab_FuBen)
        self.spb_FuBen = QtWidgets.QSpinBox(self.layoutWidget3)
        self.spb_FuBen.setObjectName("spb_FuBen")
        self.horizontalLayout_6.addWidget(self.spb_FuBen)
        self.layoutWidget4 = QtWidgets.QWidget(self.grb_list)
        self.layoutWidget4.setGeometry(QtCore.QRect(450, 20, 149, 22))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.chb_mjing = QtWidgets.QCheckBox(self.layoutWidget4)
        self.chb_mjing.setObjectName("chb_mjing")
        self.horizontalLayout_7.addWidget(self.chb_mjing)
        self.lab_MiJing = QtWidgets.QLabel(self.layoutWidget4)
        self.lab_MiJing.setObjectName("lab_MiJing")
        self.horizontalLayout_7.addWidget(self.lab_MiJing)
        self.spb_MiJing = QtWidgets.QSpinBox(self.layoutWidget4)
        self.spb_MiJing.setObjectName("spb_MiJing")
        self.horizontalLayout_7.addWidget(self.spb_MiJing)
        self.layoutWidget5 = QtWidgets.QWidget(self.grb_list)
        self.layoutWidget5.setGeometry(QtCore.QRect(30, 140, 341, 18))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chb_cjMaoYi = QtWidgets.QCheckBox(self.layoutWidget5)
        self.chb_cjMaoYi.setObjectName("chb_cjMaoYi")
        self.horizontalLayout.addWidget(self.chb_cjMaoYi)
        self.chb_gjMaoYi = QtWidgets.QCheckBox(self.layoutWidget5)
        self.chb_gjMaoYi.setObjectName("chb_gjMaoYi")
        self.horizontalLayout.addWidget(self.chb_gjMaoYi)
        self.chb_others = QtWidgets.QCheckBox(self.layoutWidget5)
        self.chb_others.setObjectName("chb_others")
        self.horizontalLayout.addWidget(self.chb_others)
        self.grb_mode = QtWidgets.QGroupBox(assist)
        self.grb_mode.setGeometry(QtCore.QRect(20, 20, 631, 51))
        self.grb_mode.setObjectName("grb_mode")
        self.chb_doubleStart = QtWidgets.QCheckBox(self.grb_mode)
        self.chb_doubleStart.setGeometry(QtCore.QRect(30, 20, 111, 16))
        self.chb_doubleStart.setObjectName("chb_doubleStart")
        self.layoutWidget6 = QtWidgets.QWidget(self.grb_mode)
        self.layoutWidget6.setGeometry(QtCore.QRect(420, 18, 192, 22))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lab_starttime = QtWidgets.QLabel(self.layoutWidget6)
        self.lab_starttime.setObjectName("lab_starttime")
        self.horizontalLayout_5.addWidget(self.lab_starttime)
        self.dte_starttime = QtWidgets.QDateTimeEdit(self.layoutWidget6)
        self.dte_starttime.setObjectName("dte_starttime")
        self.horizontalLayout_5.addWidget(self.dte_starttime)
        self.chb_playerMode = QtWidgets.QCheckBox(self.grb_mode)
        self.chb_playerMode.setGeometry(QtCore.QRect(270, 20, 121, 16))
        self.chb_playerMode.setObjectName("chb_playerMode")
        self.chb_switch = QtWidgets.QCheckBox(self.grb_mode)
        self.chb_switch.setGeometry(QtCore.QRect(160, 20, 71, 16))
        self.chb_switch.setObjectName("chb_switch")
        self.grb_process = QtWidgets.QGroupBox(assist)
        self.grb_process.setGeometry(QtCore.QRect(20, 269, 471, 71))
        self.grb_process.setObjectName("grb_process")
        self.lab_logs = QtWidgets.QLabel(assist)
        self.lab_logs.setGeometry(QtCore.QRect(20, 340, 61, 16))
        self.lab_logs.setObjectName("lab_logs")
        self.tb_notes = QtWidgets.QTextBrowser(assist)
        self.tb_notes.setGeometry(QtCore.QRect(500, 280, 261, 61))
        self.tb_notes.setObjectName("tb_notes")
        self.grb_list.raise_()
        self.grb_mode.raise_()
        self.verticalLayoutWidget.raise_()
        self.tb_logs.raise_()
        self.grb_process.raise_()
        self.lab_logs.raise_()
        self.tb_notes.raise_()

        self.retranslateUi(assist)
        QtCore.QMetaObject.connectSlotsByName(assist)

    def retranslateUi(self, assist):
        _translate = QtCore.QCoreApplication.translate
        assist.setWindowTitle(_translate("assist", "助手"))
        self.pb_start.setText(_translate("assist", "启动"))
        self.pb_pause.setText(_translate("assist", "暂停"))
        self.pb_stop.setText(_translate("assist", "停止"))
        self.pb_clear.setText(_translate("assist", "清空任务"))
        self.grb_list.setTitle(_translate("assist", "任务清单"))
        self.chb_dtu.setText(_translate("assist", "打图任务"))
        self.chb_wtu.setText(_translate("assist", "挖图任务"))
        self.chb_smen.setText(_translate("assist", "师门任务"))
        self.chb_ybiao.setText(_translate("assist", "押镖任务"))
        self.chb_wkuang.setText(_translate("assist", "挖矿任务"))
        self.chb_zgui.setText(_translate("assist", "抓鬼任务"))
        self.lab_zgui.setText(_translate("assist", "轮数"))
        self.chb_bpai.setText(_translate("assist", "帮派任务"))
        self.chb_mpai.setText(_translate("assist", "门派挑战"))
        self.chb_haidi.setText(_translate("assist", "海底寻宝"))
        self.chb_mihunt.setText(_translate("assist", "勇闯迷魂塔"))
        self.chb_jylian.setText(_translate("assist", "经验链任务"))
        self.chb_fben.setText(_translate("assist", "副本任务"))
        self.lab_FuBen.setText(_translate("assist", "数量"))
        self.chb_mjing.setText(_translate("assist", "秘境任务"))
        self.lab_MiJing.setText(_translate("assist", "头领"))
        self.chb_cjMaoYi.setText(_translate("assist", "初级贸易"))
        self.chb_gjMaoYi.setText(_translate("assist", "高级贸易"))
        self.chb_others.setText(_translate("assist", "其他任务"))
        self.grb_mode.setTitle(_translate("assist", "模式"))
        self.chb_doubleStart.setText(_translate("assist", "启用双开模式"))
        self.lab_starttime.setText(_translate("assist", "开始时间："))
        self.chb_playerMode.setText(_translate("assist", "启用组队跟随"))
        self.chb_switch.setText(_translate("assist", "主号切换"))
        self.grb_process.setTitle(_translate("assist", "执行状态"))
        self.lab_logs.setText(_translate("assist", "执行日志："))
        self.tb_notes.setHtml(_translate("assist", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">说明：</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1、需要用管理员权限进行运行</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2、目录不能包含中文</p></body></html>"))
